spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/changelog-master.yaml

  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

  logging:
    level:
      liquibase: DEBUG