CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(63) NOT NULL,
    surname VARCHAR(63) NOT NULL,
    birth_date DATE,
    email VARCHAR(63) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);